### ISSUE TITLE
I can't install Bloxstrap!

### ISSUE THREAD

**Issue by yuuxxgo** [bloxstraplabs/bloxstrap-rpc-sdk#1]
Hello, I have a problem installing Bloxstrap, I restarted my PC and turned it back on to delete the files etc in %localappdata%/bloxstrap and i do also with locate log file, I also tried to install it as administrator it doesn't work. If anyone can help me install it I would appreciate it.
![Bloxstrap Exception 19_01_2024 11_23_23](https://github.com/bloxstraplabs/bloxstrap-rpc-sdk/assets/157115399/f5778e63-bd50-41c2-a3e6-2a911d6684ce)

**Comment by GoingCrazyDude** [comment]
this is not the correct place
