### ISSUE TITLE
Update the Roblox Creator Store version to 1.1.0

### ISSUE THREAD

**Issue by 5h1b** [bloxstraplabs/bloxstrap-rpc-sdk#5]
it has seem that the [Roblox Creator Store](https://create.roblox.com/marketplace/asset/14278970228/BloxstrapRPC-SDK) version has been left on version 1.0.1 and is not on the newest version of 1.1.0, you should update it.

alternately you can update the readme to use the ID 15097513552 and not 14278970228, and also update 15097513552 to be public, plus update the description to show that it is indeed 1.1.0.

**Comment by pizzaboxer** [comment]
Fixed, thanks for letting me know.
